version: '3'
services:
  ansible:
    build: ./master
    image: scher200/ansible-lab-master:0.0.1
    volumes:
      - "./ansible/hosts:/etc/ansible/hosts"
      - "./playbooks:/root/playbooks"
    links:
      - server

  server:
    build: ./worker
    image: scher200/ansible-lab-worker:0.0.1
